version: "3.6"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3300:3306
    environment:
      - MYSQL_DATABASE=ebook_chat_app
      - MYSQL_ROOT_PASSWORD=chat_app123
      - MYSQL_USER=chat_app
      - MYSQL_PASSWORD=chat_app1123